name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Case 1
      id: case-1
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Case 1
        setup-command: ''
        command: python main.py
        input: '7'
        expected-output: Factorial of 7 is 5040
        comparison-method: contains
        timeout: 10
        max-score: 2
    - name: Case 2
      id: case-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Case 2
        setup-command: ''
        command: python main.py
        input: '13'
        expected-output: Factorial of 13 is 6227020800
        comparison-method: contains
        timeout: 10
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        CASE-1_RESULTS: "${{steps.case-1.outputs.result}}"
        CASE-2_RESULTS: "${{steps.case-2.outputs.result}}"
      with:
        runners: case-1,case-2
